### ISSUE TITLE
Can't check single package - Requires .meteor/versions to run

### ISSUE THREAD

**Issue by deanrad** [timothyarmes/packagecheck#7]
Hi - I like where you're going with this, but run in the dir of `okgrow:analytics`, I get this error

```
> packagecheck
=> Checking package okgrow:analytics...
 [Error: ENOENT, no such file or directory '.meteor/versions']
  errno: -2,
  code: 'ENOENT',
  path: '.meteor/versions',
  syscall: 'open' }
```

Are you sure you support checking a single package as your README says ?

**Comment by timothyarmes** [comment]
Hi,

PackageCheck is designed to be run from inside a Meteor project. You can check a single package by either running it from that directory or else passing the path to the package.

If, however, you try to run it on a package that isn't part of a Meteor project folder then it will effectively fail.

**Comment by deanrad** [comment]
Hi, So

> PackageCheck is designed to be run from inside a Meteor project

Contradicts the help text

```
With no arguments, 'packagecheck' will check the current directory, which can
either be a single package, a Meteor 'packages' directory or a Meteor project
directory (in the latter two cases all the individual packages will be checked).
```

Running from a package dir is what I did.

**Comment by timothyarmes** [comment]
You can run from a package dir as long as it's in a project. For example, given this structure:

```
MyApp
|- .meteor
|- packages
    |- mypackage
```

Then you can do any of these:
- `package check` from the MyApp directory
- `packagecheck packages` from the MyApp directory
- `packagecheck packages/mypackage` from the MyApp directory
- `packagecheck` from the packages directory
- `packagecheck mypackage` from the packages directory
- `packagecheck` from the packages/mypackage directory

(Do ensure that you have the latest version since there was a bug concerning this that I fixed last week)
